version: '3.8'

services:
  web:
    build: ./apache-php
    ports:
      - "8080:80"
    volumes:
      - ./htdocs:/var/www/html
    environment:
      PHP_MEMORY_LIMIT: 512M
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mariadb:11.4
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: devdb
      MARIADB_USER: dev
      MARIADB_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  testhost:
    image: halverneus/static-file-server:latest
    ports:
      - "3000:8080"
    volumes:
      - ./testhost-content:/web
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  dbdata:
